# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
 - "Vagrantfile"
 - "puphpet/"
 - "hackathon/public"
