<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('RefuseBot'))->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet('https://fezvrasta.github.io/bootstrap-material-design/dist/css/material-fullpalette.css')
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="h1 navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('RefuseBot') ?></a>
                </div>
                <div id="" class="navbar-right">
                    <p class="navbar-text text-small">
                        <span class="navbar-right">City of Phoenix <a href="http://phxinnovationgames.com/">Innovation Games</a></span>
                        <br>
                        <span class="navbar-right"><?php echo date('M d Y') ?></span>
                    </p>
                </div>
            </div>
        </nav>

        <?php echo $this->content; ?>

        <div class="container">
            <hr>
            <footer>
                <p>Please remember the <a target="_blank" href="http://swcoalition.org/2014/06/5-rs-sustainability-reduce-recycle-reuse-rot-refuse/">5 R's of sustainability</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
