<div class="container">
	<div class="row">
		<div class="col-md-12">
			<form class="form-inline" id="form-pickup-days">
				<h1 class="h2">Stop forgetting trash day!</h1>
				<h2 class="h4">Find your pickup days</h2>
				<div class="form-group">
					<label for="address" class="sr-only">Address</label>
					<input type="text" class="form-control form-control-wide" id="form-pickup-days-query" placeholder="Address (house number and street name)">
				</div>
				<button type="submit" class="btn btn-success" id="form-pickup-days-submit">Go</button>
			</form>
			<div id="results-pickup-days" class="hidden">
				<p>Your pickup days are:</p>
				<table></table>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<form class="form-inline" id="form-refusebot">
				<div class="form-group">
					<label for="form-refusebot-query"><h1 class="h2">RefuseBot, what do I do with...</h1></label>
					<textarea class="form-control" rows="3" id="form-refusebot-query" placeholder="trash"></textarea>
				</div>
				<button id="form-refusebot-submit" class="btn btn-success">Find out</button>
			</form>
		</div>
		<div class="col-md-12">
			<div id="results-refusebot">
				<div id="refusebot-message" class="speech-bubble hidden"></div>
				<div id="refusebot" class="pull-right"></div>
			</div>
		</div>
	</div>
</div>