<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="h2">Stop forgetting trash day!</h1>
			<h2 class="h4">Find your pickup days</h2>
			<form class="form-inline">
				<div class="form-group">
					<label for="address" class="sr-only">Address</label>
					<input type="text" class="form-control form-control-wide" id="address" placeholder="Address (house number and street name)">
				</div>
				<button type="submit" class="btn btn-success">Go</button>
			</form>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			<form class="form-inline" id="form-refusebot">
			<!-- <div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<strong>Warning!</strong> Better check yourself, you're not looking too good.
			</div> -->
				<div class="form-group">
					<label for="form-refusebot-query"><h1 class="h2">RefuseBot, what do I do with...</h1></label>
					<input type="input" class="form-control" id="form-refusebot-query" placeholder="trash">
				</div>
				<button id="form-refusebot-submit" class="btn btn-success" disabled="disabled">Find out</button>
			</form>
		</div>
		<div class="col-md-4">
		</div>
	</div>
</div>