<div class="container">
	<div class="row">
		<div class="col-md-8">
			<form class="form-inline" id="form-pickup-days">
				<h1 class="h2">Forget to put your trash cans out again?</h1>
				<h2 class="h4">Find your pickup days</h2>
				<div class="form-group">
					<label for="form-pickup-days-query" class="sr-only">Address</label>
					<input type="text" class="form-control form-control-wide" id="form-pickup-days-query" placeholder="Address (house number and street name)" required>
				</div>
				<button type="submit" class="btn btn-success" id="form-pickup-days-submit">Go</button>
			</form>
			<section id="results-pickup-days" class="hidden">
				<h1 class="h3">Your pickup days are:</h1>
				<table></table>
				<form class="form-inline" id="form-email">
					<h2 class="h4">Get email reminders</h2>
					<div class="form-group">
						<label for="form-email-input" class="sr-only">Email Address:</label>
						<input type="email" class="form-control form-control-wide" id="form-email-input" placeholder="email@domain.tld" required>
					</div>
					<button type="submit" class="btn btn-success" id="form-email-submit">Subscribe</button>
				</form>
			</section>
			<section id="results-email" class="alert alert-success hidden">
				<p id="results-email-message"></p>
				<br>
				<table id="results-email-reminders">
					<thead>
						<tr>
							<td colspan="2"><strong>Days</strong></td>
						</tr>
					</thead>
				</table>
			</section>
		</div>
		<!-- <div class="col-md-4">
			<section id="statistics">
				<h1 class="h4">Recycling just <strong>10% more</strong> per year could:</h1>
				<ul>
					<li>Save $1.53M, <strong>enough money to send 166.3 kids to college for a year</strong></li>
					<li>Save 233K gallons of fuel, equivalent to getting 367.058667 cars off the road.</li>
				</ul>
				<p>The total cash from that 10% increase in recycling proves garbage is a <strong>gold mine</strong> generating an additional $2.7M. This is enough to <strong>send 289 additional kids to college for a year.</strong></p>
			</section>
		</div> -->
	</div>
</div>
<div class="container-fluid infographic-panel" id="infographic-panel-average-recycle">
</div>
<div class="container">
	<div class="row" style="background-color: #fff; padding-top: 2em;">
		<div class="col-md-6">
			<form id="form-refusebot">
				<div class="form-group">
					<label for="form-refusebot-query" class="sr-only"><h1 class="h2">RefuseBot, what do I do with...</h1></label>
					<textarea class="form-control" rows="3" id="form-refusebot-query" placeholder="RefuseBot, what do I do with..." required></textarea>
				</div>
				<button type="submit" id="form-refusebot-submit" class="btn btn-success">Find out</button>
			</form>
		</div>
		<div class="col-md-12">
			<div id="results-refusebot">
				<div id="refusebot-message" class="speech-bubble hidden"></div>
				<div id="refusebot" class="pull-left"></div>
			</div>
		</div>
	</div>
</div>
<div id="refusebot-preload"></div>